### ISSUE TITLE
BX Checking for Muon Showers

### ISSUE THREAD

**Issue by aloeliger** [cms-l1t-offline/cmssw#1071]
Follow up on https://github.com/cms-sw/cmssw/pull/40773 needed.

At the moment, the MuonShowerCondition class is checking only the central BX: ReceiveMuonShowerObjectData is only looking at BX0. However, we can have showers in other BXs, too (as we saw last year with muon showers before fixing the timing). This has to be included because it can be useful for the online monitoring.

We are postponing this update because it is minor and we would like to make sure that the main fix for the emulation is entering CMSSW_13_0_0 since the beginning.

**Comment by eyigitba** [comment]
Hi @aloeliger @elfontan thanks for opening this issue! I agree that the rest of the PR is more important and this is not urgent, but isn't this a simple fix anyway? 

I thought changing https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TGlobal/src/GlobalBoard.cc#L393 to make it similar to https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TGlobal/src/GlobalBoard.cc#L357 and adding a for loop over BX range was enough. 

Are there some other changes required to implement this?

**Comment by elfontan** [comment]
Hi @eyigitba,
I had a look and indeed you are right, to modify the GlobalBoard and include the loop on the BXs is easy.
However, I thought that I needed some more development in the MuonShowerCondition class to check the condition at every BX. In fact, when I run including some printouts in the GlobalBoard (and MuShowerCondition), I always see BX to be zero, and I assumed that I was missing something.

However, I actually see the same behaviour when adding printouts in the muon part, so maybe it is simply in this way.
For my understanding, is this expected and due to the fact that if there are not showers in other BXs, the GlobalBoard do not receive anything from the other BXs and then they are not considered at all? 
(In this case, do I have any way to "validate" the code?)

If this is the case, I can update the two PRs tomorrow before we proceed to the merge.
Let me know!

Thank you very much,
--Elisa

**Comment by eyigitba** [comment]
So, I think this is one feature of showers. Since we trigger on any shower right now, I think it becomes more likely that it's in BX0 especially in physics datasets. We can look at ZB datasets and hopefully we should see showers in other BXs as well. If this is not the case, then maybe I'm missing something.

**Comment by elfontan** [comment]
A good data file to validate the update of the code to check the HMT condition for all BXs is: `/store/data/Commissioning2023/Cosmics/RAW/v2/000/365/300/00000/0bee10f0-6e0c-4efd-9ab5-c58993f0b709.root`.

Note that for run 365300, the DQM shows mismatches only for BXs -2, -1, +1, +2 (central BX was fixed by the previous PR https://github.com/cms-sw/cmssw/pull/40773): https://cmsweb.cern.ch/dqm/online/session/ezWJ9j.

Fix included in CMSSW_13_1_X (https://github.com/cms-sw/cmssw/pull/41211) and CMSSW_13_0_X (https://github.com/cms-sw/cmssw/pull/41249).
Running the DQM workflow offline on 4000 events, 13 mismatches were observed in BX 1 (the highest number, less mismatches in BX 2, BX -1, BX -2) before and zero after. This PR should complete the fix of DQM issues at uGT with HMT observed during 2022.

**Comment by aloeliger** [comment]
Closed by https://github.com/cms-sw/cmssw/pull/41211
