### ISSUE TITLE
Request for extensions to L1TNtuple

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#123]
We can track requests for needed items in L1TNtuple here.

Thomas requests additional features to L1TNtuple for uGMT studies.

```
If you do a diff with [1] you should see what I had to add to the
L1TNtuple package to get what I needed.
Joschka wrote this L1AnalyzerUGMT ntuple in the style of the L1Analyzer
ntuples with the uGMT output muons which also store information about
the input muon that was used to generate it.

And then I would also need generator info and legacy GMT info for the
studies.

Cheers,
Thomas

[1]
https://github.com/thomreis/cmssw/tree/l1t-dev-recipe-CMSSW_7_6_0_with-uGMT-ntuple
```

**Comment by mulhearn** [comment]
@jimbrooke have a look at this place.

**Comment by mulhearn** [comment]
@apana have a look too.

**Comment by jimbrooke** [comment]
I'm struggling to understand all the changes in here.  I think the new L1MuonUpgradeTreeProducer is fine.  But I see also changes to L1NtupleProducer, which I had hoped to deprecate since it is an out of date behemoth.  @thomreis do you just need the gen level info from L1NtupleProducer (with additional variables as in your repo)?  If so, I suggest we break this out into it's own producer, which can also do the MC truth vertices.

**Comment by thomreis** [comment]
I need the gen variables (pt, eta, phi, id) that I have added in my repo for the efficiency studies and the legacy GMT variables (Pt, Eta, Phi, N, CandBx, Cha, Qual, Isol, Rank, Det) for comparisons.

**Comment by mulhearn** [comment]
Not sure if this issues is still needed... leaving open for now.

**Comment by mulhearn** [comment]
This issue is unused.  Closing.
