### ISSUE TITLE
Workflow instructions

### ISSUE THREAD

**Issue by jimbrooke** [cms-l1t-offline/cmssw#146]
A suggestion for the workflow on the wiki page.  Instead of
git pull cms-l1t-offline l1t-XXXX-$CMSSW_VERSION

Which causes the history to be filled with merge commits, we could do 
git pull --rebase cms-l1t-offline l1t-XXXX-$CMSSW_VERSION

There are downsides to this, eg. if the rebase fails you have to intervene.

**Comment by mulhearn** [comment]
An alternative is to do:

```
git log
```

and take note of the commit hash <X> directly below the last commit (a merge).  Then check that:

```
git diff <X>
```

shows zero differences... and so the last commit is an empty merge commit.

So now:

```
git reset --soft <X>
```

will remove it, leaving all real commits in tact.

**Comment by mulhearn** [comment]
All of these can blow up in peoples faces, so I haven't suggested any of this, since I find the merge commits easy to ignore.

**Comment by mulhearn** [comment]
"How I Learned to Stop Worrying and Love the Merge":  This is a popular topic of debate, and I wouldn't disagree with any sane workflow philosophy, but since you brought up the topic, I'll share my (evolving) thoughts on the matter having worked through several different rebase/merges now with varied from miserable failure to straightforward success.

I started out hating the way the whole git PR mechanism essentially forces merges onto your history, and spent (I think now _wasted_) a lot of time trying to figure out to have a nice linear history.  I've recently come to the conclusion that we should for the most part only rebase when moving from one CMSSW version to another, because that is largely about unrelated code changes.  But if there's any chance of non-trivial conflicts, I now think the merge is actually better.  One practical problem is that at rebase, you have to conflict resolve at each commit, so if, e.g., a commit changes file A so that it is conflicted, but a later commit changes it in a way that it is no longer conflicted, you'll have to conflict resolve during a rebase, but the merge won't flag file A as conflicted.  There are more philosophical objections to rebase out there too, mainly that the imaginary rebased commits never really happened.  I've seen the practical fallout of this when after a rebase you then have these commits that leave the repo in a completely untested state.  Often the rebased commits even look ridiculous, or don't even compile, until a last commit that fixes the rebase change.   I guess if you want to thoroughly test at each rebase commit, by doing `git rebase --interactive` or so, you can have the linear modified history with actual legit new commits, but for the merge you only have to do this at one step, its the default, and your history clearly marks exactly what actually happened during development.

There's a good article on this topic at
  https://blog.glyphobet.net/essay/2504
which explains this in the context of a good dedicated test suite, which we are already working on.

Anyway, calling this issue closed, even though I suspect this will be one of those debates that rages endlessly on the net...
