### ISSUE TITLE
Updates for HI O2O and related changes to CaloParams. 

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#68]
First pass PRs are here:
- 80X cms-sw#12176 (Merged)
- 76X cms-sw#12180 (Merged)
- 75X cms-sw#12183 (Merged)

Second Pass PRs are here:
- 75X cms-sw#12364 Updates config files used in customization (Merged)
- 75X cms-sw#12366 Removes Customization (Superceded by following)
- 75X  cms-sw#12475 Removes Customizations plus new GT with latest HI mc tags. (tests underway)

After feedback from Alca/DB it seems our plan needs a revision.  We won't have new records for distinguishing HI from PP.  Instead, the O2O code needs to be told (either by parsing L1 key, or, for now, just hard-coded)  whether it is in HI mode or PP mode.  In HI mode, it O2Os the HI payload, placing it into the CaloParams online tag.  In PP mode, it O2Os the PP payload, placing it into the CaloParams online tag.  In addition, we also always O2O the PP payload, putting it into an explicit PP online tag.  Likewise, we always O2O the HI payload, putting it into an explicit HI online tag.

But additional work still needed to include HI configurations into the GT.

1) @kkotov needs to update the O2O, provide a new sqlite file (for HI checks), and turn this on after testing.
2) @kkotov needs to make MC tags for HI and place into offline DB.
3) Then we request new GTs for 80X heavy ion GTs. 
4) After validation, maybe those GTs are backported to 75X/76X.
5) Once in GT, we turn off customizations taking these from local config.

Once O2O is ready, we should make sure DQM takes payloads from online tags.

@richard-cms still needs to
1) Update local config files to be up to date. (DONE)
2) Remove customizations. (PR ready, waiting on GT availability)

**Comment by mulhearn** [comment]
@richard-cms @kkotov lets track this project here.

**Comment by harmonicoscillator** [comment]
Hey Mike,

I can't promise much time spent on doing this again - we're in the middle
of Heavy Ion preparation which is taking almost all of my time. You can
find the branches where the first attempt for 74X was here:
https://github.com/cms-l1t-offline/cmssw/tree/l1t-devel-CMSSW_7_4_X-CaloParamsUpdate

Alex

**Comment by mulhearn** [comment]
Understood, Alex, but presumably you can help with the part of this about adding HI parameters to CaloParams?

**Comment by mulhearn** [comment]
So we decided on the the mouthful name "L1TCaloParamsStage2Helper".

**Comment by harmonicoscillator** [comment]
Mike,

I have a branch based on 7_6_0_pre7 which includes:
1) The HI emulator development
2) The CaloParamsHelper class (same one used for Stage1 and Stage2)
3) Several new caloparams for use by HI

https://github.com/richard-cms/cmssw/tree/HIL1_FirmwareMatching_760p7

In all cases I just used iparams_[0] for the new HI params (see for example
this one:
https://github.com/richard-cms/cmssw/blob/HIL1_FirmwareMatching_760p7/L1Trigger/L1TCalorimeter/interface/CaloParamsHelper.h#L126
)

There's lots of debug statements in the branch for HI FW development right
now, but other than those I think the code is mostly correct for Stage1. I
could really use an eye on the Stage2 workflows since I moved them to
CaloParamsHelper as well and don't really know how to test.

I think that there are a few HI developments that still have to go in
(related to Centrality) but after that this is ~final.

Alex

**Comment by mulhearn** [comment]
@richard-cms a few comments, but we can live with this if your time is limited:

1) Would be better if version was always set in constructor (so e.g. eliminate "setEgNodeVersion").
Note that there is no use case for writing an obsolete version, so we will always write to the latest version.  We only need to be able to interpret obsolete version from DB.

2) Would be better if calling the setter function multiple times wouldn't have unexpected effects.
Consider what happens if you call this n times:  

```
void setEgEtaCut(int mask) { pnode_[egPUS].iparams_.push_back(mask); }
```

**Comment by mulhearn** [comment]
@jimbrooke can you have a look at alex's changes to implement plan migration of CaloParams getters/setters to a helper class is on the mark for Stage 2?

**Comment by harmonicoscillator** [comment]
Mike,

Sorry I didn't respond to your comments, was pretty deep in the saltmines.
We've just finished what I think is a "golden" HI FW version, so I will try
to address your concerns and cut a "golden" emulator branch as well,
porting it to 75X tomorrow. If you have some time to chat tomorrow (any
time after 14:00 CET) I have a few remaining O2O questions.

Alex

**Comment by mulhearn** [comment]
This will go into 80x and than back port as needed.  What actually are the needs for Heavy Ions?  What release will you use for HI online data-taking for instance?

**Comment by harmonicoscillator** [comment]
Mike,

We are using 75X for HI data taking, so I will make PRs for 80X, 76X, and
75X today (probably late today). I'm still not super sure how O2O works,
would you mind pointing me to the current O2O ESProducer, and I can think
about what we need to do for HI?

Alex

**Comment by harmonicoscillator** [comment]
Okay regarding your comment

> > > there is no use case for writing an obsolete version

I actually do have a use case for that in this branch, and it is the region PUS parameters used by pp. The branch that I'm merging from July used a LUT for the parameters, and that was version 1. However we never actually moved to using it, so I still need to produce settings where 
pnode_[regionPUS].version_ = 0
while hiCentrality etc. are version 1. CaloParams uses the default constructor for the nodes, so I think I either have to change the default constructor to 1 for everyone or set each version manually. 

I'm now fixing your comment two so that multiple calls of setRegionMask don't break everything (I'm just going to fix the iparams vector size and future me will have to patch CaloParamsHelper if the size changes).

**Comment by mulhearn** [comment]
@richard-cms:  in this case, just blow away pnode_[regionPUS].version_=1.  The only reason to add a higher version is if we are actually going to use it...  Consider that part an exercise of this evolution feature to make sure we can use it in future if necessary... but not necessary here (since O2O simply adapted.)

**Comment by harmonicoscillator** [comment]
Okay will do.

**Comment by mulhearn** [comment]
@kkotov:  can you coordinate with @richard-cms on the updates to the Stage-1 CaloParams online producer?  Timescale for this is sooner than I expect.

**Comment by harmonicoscillator** [comment]
The emulator PRs are up:
#12176 , #12180 , #12183

**Comment by mulhearn** [comment]
I'm on board for the PRs in 75X and 80X, but I'm loath to mess with 76X write before the close.

**Comment by mulhearn** [comment]
How goes the unpacker?

**Comment by harmonicoscillator** [comment]
Mike,

HI doesn't care about 76X, we expect to take data in 75X.

I'm not sure what you mean about the unpacker? I'm pretty sure the current Stage 1 unpacker works fine for us?

**Comment by mulhearn** [comment]
Pinged the alca/db folks to sign.

**Comment by mulhearn** [comment]
The PR with the new HI MC GTs is here:  cms-sw#12474

I'll merge with cms-sw#12366.

**Comment by harmonicoscillator** [comment]
Great sounds good.

Which release will this end up in, I've started to lose track. 7_5_5_patch4, or a 7_5_6?

**Comment by mulhearn** [comment]
I guess 7_5_6 is the plan...

**Comment by mulhearn** [comment]
Combined PR with new GT plus removal of customizations is here:  cms-sw#12475

**Comment by mulhearn** [comment]
This one has been closed for some time.
