### ISSUE TITLE
Default cmsDriver command looking for GEM Digis in 2018 era

### ISSUE THREAD

**Issue by davignon** [cms-l1t-offline/cmssw#749]
I tried following the instructions here:
`https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TStage2Instructions`
And run on the following MC sample:
`/VBFHToTauTau_M125_13TeV_powheg_pythia8/RunIIAutumn18DR-FlatPU28to62NZS_102X_upgrade2018_realistic_v15-v1/GEN-SIM-RAW`
Using this cmsDriver command:
```
cmsDriver.py l1Ntuple -s RAW2DIGI --python_filename=mc.py -n 240 --no_output --era=Run2_2018 --mc --conditions=102X_mcRun2_asymptotic_v3 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulMCFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleRAWEMU --customise=L1Trigger/Configuration/customiseSettings.L1TSettingsToCaloParams_2018_v1_2 --filein=/store/mc/RunIIAutumn18DR/VBFHToTauTau_M125_13TeV_powheg_pythia8/GEN-SIM-RAW/FlatPU28to62NZS_102X_upgrade2018_realistic_v15-v1/60000/9151C8E3-F152-9341-9898-C73B24E40640.root
```
yields this error to me:
```
----- Begin Fatal Exception 08-Mar-2019 17:29:57 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing global begin Run run: 1
   [1] Calling method for module GEMRawToDigiModule/'muonGEMDigis'
Exception Message:
No "GEMELMapRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```
Does anyone know why it's looking for GEMs in the 2018 era and how to solve this problem? Thanks a lot!

**Comment by gkaratha** [comment]
Dear Olivier,

The I think the problem is that you use an old GT. Please use a newer one [*]. I tested in your file that with this change the code finishes properly[**]  and the L1 flat root tree is produced. Let me know if it does not work for you. Thanks.

Best regards,
George

[*]  l1Ntuple -s RAW2DIGI --python_filenac.py -n 240 --no_output --era=Run2_2018 --mc --conditions=102X_upgrade2018_realistic_v15 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulMCFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleRAWEMU --customise=L1Trigger/Configuration/customiseSettings.L1TSettingsToCaloParams_2018_v1_2 --filein=/store/mc/RunIIAutumn18DR/VBFHToTauTau_M125_13TeV_powheg_pythia8/GEN-SIM-RAW/FlatPU28to62NZS_102X_upgrade2018_realistic_v15-v1/60000/9151C8E3-F152-9341-9898-C73B24E40640.root

[**]MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 L1Prompt             -w L1EventTreeProdu                       1        1
    2 XrdAdaptor           -w file_open                              1        1
    3 XrdAdaptorInternal   -w file_open                              2        2
    4 fileAction           -s file_close                             1        1
    5 fileAction           -s file_open                              3        3

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 L1Prompt             pre-events                        
    2 XrdAdaptor           pre-events                        
    3 XrdAdaptorInternal   pre-events       pre-events       
    4 fileAction           PostGlobalEndRun                  
    5 fileAction           pre-events       pre-events       pre-events

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
Warning                 4                   4
System

**Comment by davignon** [comment]
Hi George,
Thanks a lot I will try this. If it works I will update the instructions on the TWiki that are outdated...
Cheers,
Olivier

**Comment by gkaratha** [comment]
Dear Olivier,

No problem ! Let me know if it does not work for you.

Best regards,
George

**Comment by davignon** [comment]
Thanks. It worked. I updated the instructions and I'm now closing this issue.
